### ISSUE TITLE
Replace OAuth with native FB login?

### ISSUE THREAD

**Issue by zachheine** [cleechtech/ionic-firebase-auth-starter#1]
https://github.com/Wizcorp/phonegap-facebook-plugin....

**Comment by jasonshark** [comment]
I followed [this tutorial](https://blog.nraboy.com/2015/03/sign-into-firebase-with-facebook-using-ionic-framework/) on setting up ionic with firebase facebook login.

```
We are using $cordovaOauth.facebook to get an access token using a web flow and then passing this access token into the Firebase $authWithOAuthToken method.  Firebase will then validate that your access token is correct.
```
